services:
  # ---- 开发容器（热重载 / CGO / 依赖齐全）----
  app:
    build:
      context: .               # 以项目根目录为构建上下文
      target: dev              # 使用 Dockerfile 的 dev 阶段
    image: ancheymailtracker:dev         # 本地开发镜像名（可改）
    working_dir: /app
    command: air -c .air.toml
    volumes:
      - .:/app:cached          # 将当前项目挂载进容器（热重载依赖这个）
      - ./geo_db:/app/geo_db:ro
      - gocache:/go/pkg/mod    # Go module 缓存
      - gobuild:/root/.cache/go-build  # Go build 缓存
    env_file:
      - .env
      - .env.development
      - .env.settings.local
    environment:
      CITY_MMDB: "/app/geo_db/GeoLite2-City.mmdb"
      ASN_MMDB: "/app/geo_db/GeoLite2-ASN.mmdb"
    ports:
      - "8080:8080"            # 暴露应用端口（与代码监听一致）
      - "2345:2345"            # 预留给 delve 远程调试（可删）
    healthcheck:
      test: [ "CMD", "bash", "-c", "wget -qO- http://localhost:8080/healthy || exit 1" ]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 10s

  # ---- 生产容器（使用 runtime 阶段构建出的精简镜像）----
  app-prod:
    build:
      context: .
      target: runtime          # 使用 Dockerfile 的 runtime 阶段
    image: ancheymailtracker:prod         # 生产镜像名（用于本机验证或推仓库）
    env_file:
      - .env
    environment:
      CITY_MMDB: "/app/geo_db/GeoLite2-City.mmdb"
      ASN_MMDB: "/app/geo_db/GeoLite2-ASN.mmdb"
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
      - ./geo_db:/app/geo_db:ro
    healthcheck:
      test: [ "CMD", "bash", "-c", "wget -qO- http://localhost:8080/healthy || exit 1" ]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 60s
volumes:
  gocache:
  gobuild:
